### ISSUE TITLE
bad routes

### ISSUE THREAD

**Issue by suhassumukh** [kashyap07/ux-design-tool#1]
generic routes can mean security vulnerability. here, they also cause 500 internal errors. 

```
raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound
```

**Comment by kashyap07** [comment]
Ye, that was some temporary stuff. We'll separate them out later.   
Also, I don't seem to get any ```TemplateNotFound```.

**Comment by suhassumukh** [comment]
You do, esp. when chrome keeps sending out those `favicon` requests. but you could keep it open until this is resolved.
